# Иконка организма
icon: 🐻
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 16
# Вес организма
weight: 500
# Минимальный возраст для размножения
minimumReproductiveAge: 4
# Число потомков, получаемых в результате размножения
offspringCount: 2
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 2
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 5


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 2
# Число попыток охоты за ход
huntTryCount: 2
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 80
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 15
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 2
