# Иконка организма
icon: 🐍
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 12
# Вес организма
weight: 15
# Минимальный возраст для размножения
minimumReproductiveAge: 2
# Число потомков, получаемых в результате размножения
offspringCount: 3
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 5
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 30


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 1
# Число попыток охоты за ход
huntTryCount: 1
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 8
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 0.5
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 1
