# Иконка организма
icon: 🐛
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 1
# Вес организма
weight: 0.01
# Минимальный возраст для размножения
minimumReproductiveAge: 1
# Число потомков, получаемых в результате размножения
offspringCount: 3
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 100
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 1000


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 0
# Число попыток охоты за ход
huntTryCount: 3
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 1
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 0.1
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 0
