# Иконка организма
icon: 🦆
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 3
# Вес организма
weight: 1
# Минимальный возраст для размножения
minimumReproductiveAge: 1
# Число потомков, получаемых в результате размножения
offspringCount: 4
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 50
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 200


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 4
# Число попыток охоты за ход
huntTryCount: 2
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 0.15
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 0.005
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 0.005
