# Иконка организма
icon: 🦅
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 15
# Вес организма
weight: 6
# Минимальный возраст для размножения
minimumReproductiveAge: 2
# Число потомков, получаемых в результате размножения
offspringCount: 3
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 3
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 20


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 3
# Число попыток охоты за ход
huntTryCount: 4
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 1
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 0.15
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 0.05
