# Иконка организма
icon: 🐐
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 10
# Вес организма
weight: 60
# Минимальный возраст для размножения
minimumReproductiveAge: 2
# Число потомков, получаемых в результате размножения
offspringCount: 1
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 30
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 140


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 3
# Число попыток охоты за ход
huntTryCount: 2
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 10
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 2
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 2
