# Иконка организма
icon: 🌱
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 5
# Вес организма
weight: 1
# Минимальный возраст для размножения
minimumReproductiveAge: 0
# Число потомков, получаемых в результате размножения
offspringCount: 30
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 100
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 200