# Иконка организма
icon: 🐎
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 18
# Вес организма
weight: 400
# Минимальный возраст для размножения
minimumReproductiveAge: 3
# Число потомков, получаемых в результате размножения
offspringCount: 1
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 10
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 20


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 4
# Число попыток охоты за ход
huntTryCount: 3
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 60
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 2
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 1
