# Иконка организма
icon: 🐁
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 5
# Вес организма
weight: 0.05
# Минимальный возраст для размножения
minimumReproductiveAge: 1
# Число потомков, получаемых в результате размножения
offspringCount: 10
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 150
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 500


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 1
# Число попыток охоты за ход
huntTryCount: 1
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 0.01
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 0.005
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 0.005
