# Иконка организма
icon: 🐇
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 5
# Вес организма
weight: 2
# Минимальный возраст для размножения
minimumReproductiveAge: 1
# Число потомков, получаемых в результате размножения
offspringCount: 5
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 50
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 150


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 2
# Число попыток охоты за ход
huntTryCount: 1
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 0.45
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 0.25
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 0.25
