baseClassName: AbstractIslandAnimal
# Иконка организма
icon: 🐑
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 5
# Вес организма
weight: 70
# Минимальный возраст для размножения
minimumReproductiveAge: 1
# Число потомков, получаемых в результате размножения
offspringCount: 2
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 40
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 140


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 3
# Число попыток охоты за ход
huntTryCount: 3
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 15
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 4
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 2
