# Иконка организма
icon: 🌳
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 25
# Вес организма
weight: 3
# Минимальный возраст для размножения
minimumReproductiveAge: 5
# Число потомков, получаемых в результате размножения
offspringCount: 6
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 50
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 20