# Иконка организма
icon: 🐺
# Время жизни (Через сколько ходов наступить смерть)
lifeSpan: 15
# Вес организма
weight: 50
# Минимальный возраст для размножения
minimumReproductiveAge: 2
# Число потомков, получаемых в результате размножения
offspringCount: 3
# Число особей данного организма на клетке при создании клетки
defaultNumberIndividualsInCell: 15
# Максимальное число особей данного организма на клетке
maxNumberIndividualsInCell: 30


# Максимальная скорость перемещения (число клеток за ход)
maxSpeed: 3
# Число попыток охоты за ход
huntTryCount: 10
#Сколько килограммов пищи нужно животному для полного насыщения
foodRequirement: 8
# Затрата энергии (уменьшение текущего уровня насыщения ) за ход, по умолчанию
defaultFoodConsumption: 1
# Затрата энергии (уменьшение текущего уровня насыщения ) на передвижение на клетку
movementFoodConsumption: 0.5
